IF(CONFIG_BOOT_EFI_PACK)
		FIND_PROGRAM(PROGRAM_DD "dd")
		FIND_PROGRAM(PROGRAM_MMD "mmd")
		FIND_PROGRAM(PROGRAM_MCOPY "mcopy")
		FIND_PROGRAM(PROGRAM_MFORMAT "mformat")

		SET(EFI_BOOT_IMAGE ${PROJECT_BINARY_DIR}/oasys-${OASYS_VERSION}.img)
		SET(EFI_BOOTLOADER ${PROJECT_BINARY_DIR}/boot/BOOTX64.EFI)

		ADD_CUSTOM_COMMAND(
			OUTPUT ${EFI_BOOT_IMAGE}
			DEPENDS BOOTX64.EFI
			COMMAND ${PROGRAM_DD} if=/dev/zero of=${EFI_BOOT_IMAGE} bs=1k count=1440
			COMMAND ${PROGRAM_MFORMAT} -i ${EFI_BOOT_IMAGE} -f 1440 ::
			COMMAND ${PROGRAM_MMD} -i ${EFI_BOOT_IMAGE} ::/EFI
			COMMAND ${PROGRAM_MMD} -i ${EFI_BOOT_IMAGE} ::/EFI/BOOT
			COMMAND ${PROGRAM_MCOPY} -i ${EFI_BOOT_IMAGE} ${EFI_BOOTLOADER} ::/EFI/BOOT)

		ADD_CUSTOM_TARGET(BootImage ALL
			DEPENDS ${EFI_BOOT_IMAGE})
	ENDIF()