SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc)
SET(CMAKE_ASM_COMPILER x86_64-w64-mingw32-gcc)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_COMPILE_OPTIONS -I/usr/local/include/efi -ffreestanding)
SET(CMAKE_LINK_OPTIONS -nostdlib -Wl,-dll -shared -Wl,--subsystem,10 -e efi_main)
